


SRCS =  $(PATHCORE)/sim_topology.cc		\
	$(PATHCORE)/sim_data_double.cc 		\
	$(PATHCORE)/sim_data_exp.cc 		\
	$(PATHCORE)/sim_matrix.cc 		\
	$(PATHCORE)/sim_networkop.cc

MAINS = $(PATHPROJ)/main.cc


